server:
  port: 8004

spring:
  application:
    name: payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.91.151.48:3306/punic?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: punici
    password: punici
  cloud:
    zookeeper:
      connect-string: 119.91.151.48:2181


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.punici.cloud.payment8004.entity

swagger:
  enabled: true